[project]
name = "mcp-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=0.3.7",
    "langchain-openai>=0.3.28",
    "mcp-use>=1.3.8",
]
